# UGST4012 - Digital Tools for the Social Sciences 
## Central European University, Winter 2020/2021
## LAB 1
Author: Gabriela Juncosa, PhD

### types
|Type|Name|Example
|---|---|---
|int|Integer|30,-4
|float|Floating point|1.5,1e10
|str|String|"alma","c"
|bool|Boolean|True,False
|list|List|\[1,"alma",2\]
|dict|Dictionary|\{'course': "SciPy", 'teacher': "JT"\}

In [1]:
a = 7
b = 3.14

c = True
d = "alma"
e = [1, 2]
d = {'course': "SciPy", 'teacher': "JT", }
type(a),type(b),type(c),type(d),type(e)

(int, float, bool, dict, list)

In [2]:
list1 = [1,3,5,7,9]

In [3]:
list1[5]

IndexError: list index out of range

In [4]:
list1[4]

9

In [5]:
list1[-1]

9

name_function(arguments)

In [6]:
len(list1)

5

In [8]:
type(list1)

list

In [9]:
type(list1[0])

int

In [11]:
name = ['Amelia', 'Laura','Fikhar']
age = [18,21,19]
height = [1.80, 1.53, 1.70]

In [12]:
print(type(name),type(age),type(height))

<class 'list'> <class 'list'> <class 'list'>

In [13]:
print(type(name[0]),type(age[0]),type(height[0]))

<class 'str'> <class 'int'> <class 'float'>

In [14]:
class_info = [['Amelia', 'Laura','Fikhar'],[18,21,19] ,[1.80, 1.53, 1.70]]

In [15]:
type(class_info)

list

In [16]:
len(class_info)

3

In [21]:
type(class_info[0])

list

In [22]:
class_info[0][0]

'Amelia'

In [23]:
type(class_info[0][0])

str

In [25]:
class_info[1][1]

21

In [27]:
print(range(len(class_info)))

range(0, 3)

In [31]:
for i in range(len(class_info)):
    print(class_info[i][2])

Fikhar
19
1.7

In [33]:
for item in class_info: 
    print(item[1])

Laura
21
1.53

### List

In [2]:
a = [ 7, 3 ,8, 10, 7, 1, 9, 1, 5]
print(a)
print(type(a))

[7, 3, 8, 10, 7, 1, 9, 1, 5]
<class 'list'>

In [3]:
print(a[0])
print(a[0:4])
print(a[-1])

7
[7, 3, 8, 10]
5

In [5]:
a = [1, "a", [1, 2], {"name", "Torok"}]
print(a[0], a[1], a[2], a[3])

1 a [1, 2] {'name', 'Torok'}

In [6]:
a += [ "körte", True ]
print(a)

[1, 'a', [1, 2], {'name', 'Torok'}, 'körte', True]

In [ ]:
b = []
a = [ 1, 2 ]
print(b)
b.append("a")
b.append(5)
b.append(a)
print(b)
b.remove("a")
print("a removed:", b)
print(b)
print("Pop",b.pop())
a.reverse()
print("a reversed:",a)

In [ ]:
print(list(range(10)))
print(list(range(3,10,2)))

### Strings

In [8]:
s = "Hello world!"
print(s)

Hello world!

In [ ]:
print(s[0],s[1],s[-1],s[-2])
print(s[0:4],s[:4])
print(s[0:-1])
print(s[0:-1:2],s[::2])

#### Useful string methods

In [9]:
s = "Helló világ!\n"
print(s[6:].capitalize() + "XXX")
print(s.rstrip() + "YYY")
print(s.count("l"))
print(s.index("l"))
print("123".isdigit(),"1e3".isdigit(),s.isprintable(),"Körte".isprintable())
print(s.split("l"))
print(s.strip("\n! lH"))
print(s.upper())

Világ!
XXX
Helló világ!YYY
3
2
True False False True
['He', '', 'ó vi', 'ág!\n']
elló világ
HELLÓ VILÁG!

### Basic python instructions

Let's start learning how to read the documentation. (and let's do a recap of python's control flow statements.)
From the <a href="https://docs.python.org/3/reference/compound_stmts.html">reference guide</a>:

#### The while statement

The while statement is used for repeated execution as long as an expression is true:

<code>
while_stmt ::=  "while" expression ":" suite
                ["else" ":" suite]
</code> 
<code>
suite         ::=  stmt_list NEWLINE | NEWLINE INDENT statement+ DEDENT<br>
statement     ::=  stmt_list NEWLINE | compound_stmt<br>
stmt_list     ::=  simple_stmt (";" simple_stmt)* [";"]
</code>

This repeatedly tests the expression and, if it is true, executes the first suite; if the expression is false (which may be the first time it is tested) the suite of the else clause, if present, is executed and the loop terminates.

A break statement executed in the first suite terminates the loop without executing the else clause’s suite. A continue statement executed in the first suite skips the rest of the suite and goes back to testing the expression.

In [ ]:
f = 1.0
v = 1.0
while f * v < 1e10:
    f *= v
    v += 1.0
print("The largest factorial less than 1e10 is: %d! = %g" % (v - 1, f))

#### The if statement

<code>
if_stmt ::=  "if" expression ":" suite
                ("elif" expression ":" suite)*
                ["else" ":" suite]
</code>

#### The for statement

<code>
for_stmt ::=  "for" target_list "in" expression_list ":" suite
                 ["else" ":" suite]
</code>

In [ ]:
for a in range(10):
    if a < 5:
        print(a)
    else:
        print(10-a)

### Dictionaries

Dictionaries are also like lists, except that each element is a key-value pair. The syntax for dictionaries is `{key1 : value1, key2 : value 2, ...}`:

In [ ]:
D = {0 : k for k in ['a', 'b', 'c']}
print(D)

In [ ]:
fruits = {"bananas" : 1,
          "oranges" : 2,
          "apples" : 3,}

print(type(fruits))
print(fruits)

In [ ]:
type(fruits.values())

In [ ]:
print("bananas = " + str(fruits["bananas"]))
print("oranges = " + str(fruits["oranges"]))
print("apples = " + str(fruits["apples"]))

In [ ]:
fruits["bananas"] = "no bananas"
fruits["oranges"] = 100

# add a new entry
fruits["pineapples"] = "D"

print("bananas = " + str(fruits["bananas"]))
print("oranges = " + str(fruits["oranges"]))
print("apples = " + str(fruits["apples"]))
print("pineapples = " + str(fruits["pineapples"]))

Strings, numbers, and tuples work as keys, and any type can be a value. Other types may or may not work correctly as keys (strings and tuples work cleanly since they are immutable). Looking up a value which is not in the dict throws a KeyError -- use "in" to check if the key is in the dict, or use dict.get(key) which returns the value or None if the key is not present (or get(key, not-found) allows you to specify what value to return in the not-found case).

In [ ]:
print(fruits['bananas'])     ## Simple lookup, returns 'bananas'

If you try to access something that does not exists in the dictionary, you will get an error:

In [ ]:
print(fruits['strawberries'])

To avoid key errors, you can simply check with an ``if`` that the key is present in the dictionary:

In [ ]:
if 'bananas' in fruits: print(fruits['bananas']) ## Yes, you can also write an if in this way 

if 'strawberries' in fruits: print (fruits['strawberries']) ## and an if-else in this way 
else: print("I don\'t know what a strawberry is")

An alternative way to access keys in a dictionary is with the method ``get``. If the key does not exist you get a None:

In [ ]:
print(fruits.get('bananas'))
print(fruits.get('strawberries'))

To iterate over key-value pairs of a dictionary:

In [ ]:
for key in fruits: 
    print(key, fruits[key])

This iteration is equivalent to iterating over ```fruits.keys()```:

In [ ]:
for key in fruits.keys(): 
    print(key)

In [ ]:
type(fruits.keys())

If you want to show the values instead:

In [ ]:
for value in fruits.values():
    print(value)

In [ ]:
type(fruits.values)

If you want to show both at the same time, you can use fruits.items()

In [ ]:
for key, value in fruits.items():
    print(key + " = " + str(value))

_**Note that the keys are not sorted, nor are listed in the order you added them to the dictionary!**_ If you want to do that, you should sort the keys first

In [ ]:
for key in sorted(fruits.keys()):
    print(key, fruits[key])

In [ ]:
for value in sorted(fruits.values()):
    print(value)

### Dataframes with Pandas 

https://pandas.pydata.org/docs/

In [12]:
import pickle

with open("cnnVidsInfo.txt", "rb") as fp:
    rawDta = pickle.load(fp)

20000

In [13]:
print(len(rawDta))
print(type(rawDta))

20000
<class 'list'>

In [15]:
print(rawDta[0])
print(type(rawDta[0]))

{'kind': 'youtube#playlistItem', 'etag': 'bCIpIP-RN2sbOrhzCDnV4ADvdyc', 'id': 'VVV1cHZaRy01a29fZWlYQXVwYkRmeFd3LnQ4Tk8tRGVRR0lB', 'snippet': {'publishedAt': '2021-01-11T14:16:13Z', 'channelId': 'UCupvZG-5ko_eiXAupbDfxWw', 'title': "'Untethered from reality': Alisyn Camerota calls out Trump supporters", 'description': "CNN's Alisyn Camerota shares her thoughts on the President's supporters after pro-Trump rioters stormed the US Capitol. #CNN #News", 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/t8NO-DeQGIA/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/t8NO-DeQGIA/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/t8NO-DeQGIA/hqdefault.jpg', 'width': 480, 'height': 360}, 'standard': {'url': 'https://i.ytimg.com/vi/t8NO-DeQGIA/sddefault.jpg', 'width': 640, 'height': 480}, 'maxres': {'url': 'https://i.ytimg.com/vi/t8NO-DeQGIA/maxresdefault.jpg', 'width': 1280, 'height': 720}}, 'channelTitle': 'CNN', 'playlistId': 'UUupvZG-5ko_eiXAupbDfxWw', 'position': 0, 'resourceId': {'kind': 'youtube#video', 'videoId': 't8NO-DeQGIA'}}}
<class 'dict'>

In [16]:
rawDta[0].keys()

dict_keys(['kind', 'etag', 'id', 'snippet'])

In [17]:
rawDta[0]['snippet'].keys()

dict_keys(['publishedAt', 'channelId', 'title', 'description', 'thumbnails', 'channelTitle', 'playlistId', 'position', 'resourceId'])

In [18]:
rawDta[0]['snippet']['resourceId'].keys()

dict_keys(['kind', 'videoId'])

In [19]:
dataframe = []
for i in range(len(rawDta)):
    aux = (rawDta[i]['snippet']['channelTitle'],
           rawDta[i]['snippet']['channelId'], 
           rawDta[i]['snippet']['publishedAt'],
           rawDta[i]['snippet']['resourceId']['videoId'], 
           rawDta[i]['snippet']['title'], 
           rawDta[i]['snippet']['description'])
    
    dataframe.append(aux)

In [20]:
dataframe[0]

('CNN',
 'UCupvZG-5ko_eiXAupbDfxWw',
 '2021-01-11T14:16:13Z',
 't8NO-DeQGIA',
 "'Untethered from reality': Alisyn Camerota calls out Trump supporters",
 "CNN's Alisyn Camerota shares her thoughts on the President's supporters after pro-Trump rioters stormed the US Capitol. #CNN #News")

In [23]:
import pandas as pd 

videoInfo = pd.DataFrame(dataframe, 
                            columns = ['channelTitle', 'channelId', 'publishedAt',
                                       'videoId', 'title', 'description'])
videoInfo.head()

,channelTitle,channelId,publishedAt,videoId,title,description
0,CNN,UCupvZG-5ko_eiXAupbDfxWw,2021-01-11T14:16:13Z,t8NO-DeQGIA,'Untethered from reality': Alisyn Camerota cal...,CNN's Alisyn Camerota shares her thoughts on t...
1,CNN,UCupvZG-5ko_eiXAupbDfxWw,2021-01-11T13:25:33Z,BgEU7qIYzhI,Why Colin Powell says he no longer considers h...,Former Secretary of State Colin Powell weighs ...
2,CNN,UCupvZG-5ko_eiXAupbDfxWw,2021-01-10T18:49:59Z,jEtpKUUxVGQ,King: We thought these Covid-19 numbers were b...,CNN's John King breaks down the latest numbers...
3,CNN,UCupvZG-5ko_eiXAupbDfxWw,2021-01-10T18:10:10Z,gmpkorhW8hQ,Tapper: Will there be any consequences for the...,CNN's Jake Tapper reviews the violent events t...
4,CNN,UCupvZG-5ko_eiXAupbDfxWw,2021-01-09T19:35:42Z,uRsf-MYO8DA,More arrests made after riots at the US Capitol,Federal prosecutors have charged three individ...

In [24]:
videoInfo['month'] = [int(videoInfo['publishedAt'][i][5:7]) for i in range(len(videoInfo['publishedAt']))]
videoInfo['year'] = [int(videoInfo['publishedAt'][i][:4]) for i in range(len(videoInfo['publishedAt']))]
videoInfo['day'] = [int(videoInfo['publishedAt'][i][8:10]) for i in range(len(videoInfo['publishedAt']))]

videoInfo.head()

,channelTitle,channelId,publishedAt,videoId,title,description,month,year,day
0,CNN,UCupvZG-5ko_eiXAupbDfxWw,2021-01-11T14:16:13Z,t8NO-DeQGIA,'Untethered from reality': Alisyn Camerota cal...,CNN's Alisyn Camerota shares her thoughts on t...,1,2021,11
1,CNN,UCupvZG-5ko_eiXAupbDfxWw,2021-01-11T13:25:33Z,BgEU7qIYzhI,Why Colin Powell says he no longer considers h...,Former Secretary of State Colin Powell weighs ...,1,2021,11
2,CNN,UCupvZG-5ko_eiXAupbDfxWw,2021-01-10T18:49:59Z,jEtpKUUxVGQ,King: We thought these Covid-19 numbers were b...,CNN's John King breaks down the latest numbers...,1,2021,10
3,CNN,UCupvZG-5ko_eiXAupbDfxWw,2021-01-10T18:10:10Z,gmpkorhW8hQ,Tapper: Will there be any consequences for the...,CNN's Jake Tapper reviews the violent events t...,1,2021,10
4,CNN,UCupvZG-5ko_eiXAupbDfxWw,2021-01-09T19:35:42Z,uRsf-MYO8DA,More arrests made after riots at the US Capitol,Federal prosecutors have charged three individ...,1,2021,9

In [26]:
videoInfo_fil = videoInfo[videoInfo['year'] == 2020] 
print(videoInfo_fil)

     channelTitle                 channelId           publishedAt  \
85            CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-12-31T23:24:43Z
86            CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-12-31T18:44:47Z
87            CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-12-31T16:47:50Z
88            CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-12-31T16:35:42Z
89            CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-12-31T04:50:14Z
...           ...                       ...                   ...
3055          CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-01-01T12:08:58Z
3056          CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-01-01T08:59:58Z
3057          CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-01-01T06:35:43Z
3058          CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-01-01T06:14:33Z
3059          CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-01-01T06:06:07Z

          videoId                                              title  \
85    O3sLnIVQqlw  140 House Republicans expected to oppose Biden...
86    Ce14WTJ0XWU  Don Lemon rolls the tape on Trump's 2020 'insa...
87    yK2bmGnKLYw  'Stomach-churning': Romans calls out GOP hypoc...
88    EMYlhSexV9E  Former senator objected to 2004 election resul...
89    BWPoDkUitBo  Audio tapes show Melania Trump saying she has ...
...           ...                                                ...
3055  UpsbkRnQ8_s         Protests continue at US embassy in Baghdad
3056  WpOAlEPX4S4  North Korea indicates it could resume nuclear ...
3057  0qz056RwWd8   See New Year's Eve celebrations around the world
3058  pYXFWzzmmo0  'SNL' alum revives Barbara Walters character, ...
3059  wV9Z1qlP5ZQ  CNN anchor's NYE outfit cracks Anderson Cooper up

                                            description  month  year  day
85    Two Republican members of the House of Represe...     12  2020   31
86    CNN's Don Lemon reviews President Donald Trump...     12  2020   31
87    Christine Romans criticizes President Trump an...     12  2020   31
88    Former California Sen. Barbara Boxer, who obje...     12  2020   31
89    First Lady Melania Trump is heard saying she h...     12  2020   31
...                                                 ...    ...   ...  ...
3055  As demonstrations at the US embassy in Baghdad...      1  2020    1
3056  North Korean leader Kim Jong-Un seemed to indi...      1  2020    1
3057  For one night the world comes together and cel...      1  2020    1
3058  'Saturday Night Live' alum Cheri Oteri joins A...      1  2020    1
3059  Anderson Cooper and Andy Cohen kick off the Ne...      1  2020    1

[2975 rows x 9 columns]

In [27]:
videoInfo_fil = videoInfo_fil[videoInfo_fil['month'] > 8] 
print(videoInfo_fil)

    channelTitle                 channelId           publishedAt      videoId  \
85           CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-12-31T23:24:43Z  O3sLnIVQqlw
86           CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-12-31T18:44:47Z  Ce14WTJ0XWU
87           CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-12-31T16:47:50Z  yK2bmGnKLYw
88           CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-12-31T16:35:42Z  EMYlhSexV9E
89           CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-12-31T04:50:14Z  BWPoDkUitBo
..           ...                       ...                   ...          ...
868          CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-09-01T14:05:08Z  DdOGbxZeQGU
869          CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-09-01T13:22:55Z  Hp2KI7A8440
870          CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-09-01T04:54:16Z  a5COvnGH_Zg
871          CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-09-01T04:15:54Z  UH2dqHFOOlo
872          CNN  UCupvZG-5ko_eiXAupbDfxWw  2020-09-01T00:11:02Z  9ixTaQpfGog

                                                 title  \
85   140 House Republicans expected to oppose Biden...
86   Don Lemon rolls the tape on Trump's 2020 'insa...
87   'Stomach-churning': Romans calls out GOP hypoc...
88   Former senator objected to 2004 election resul...
89   Audio tapes show Melania Trump saying she has ...
..                                                 ...
868       Why Trump can’t say what he wants to do next
869  2016 Trump voter: No President has ruined the ...
870  Kenosha mayor: I am disappointed that Trump is...
871  Rep. Scalise promoted doctored video of Joe Bi...
872  Reporter asks Trump to condemn Kenosha shooter...

                                           description  month  year  day
85   Two Republican members of the House of Represe...     12  2020   31
86   CNN's Don Lemon reviews President Donald Trump...     12  2020   31
87   Christine Romans criticizes President Trump an...     12  2020   31
88   Former California Sen. Barbara Boxer, who obje...     12  2020   31
89   First Lady Melania Trump is heard saying she h...     12  2020   31
..                                                 ...    ...   ...  ...
868  President Donald Trump has always spoken in bi...      9  2020    1
869  CNN's Alisyn Camerota speaks with a panel of s...      9  2020    1
870  Kenosha, Wisconsin Mayor John Antaramian tells...      9  2020    1
871  Twitter labeled a video promoted by House Mino...      9  2020    1
872  When asked about the ongoing protests in Portl...      9  2020    1

[788 rows x 9 columns]